-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', BD.BOARD_ID, '/',FILE_ID, FILE_NAME, FILE_EXT ) AS FILE_PATH
FROM USED_GOODS_BOARD BD JOIN USED_GOODS_FILE FL ON BD.BOARD_ID = FL.BOARD_ID
WHERE VIEWS IN (SELECT MAX(VIEWS)
FROM USED_GOODS_BOARD)
ORDER BY FILE_ID DESC