-- 코드를 입력하세요
SELECT MP.MEMBER_NAME, RS.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d')
FROM MEMBER_PROFILE MP
JOIN REST_REVIEW RS
ON MP.MEMBER_ID = RS.MEMBER_ID
WHERE MP.MEMBER_ID = (SELECT MEMBER_ID
                      FROM REST_REVIEW
                      GROUP BY MEMBER_ID
                      ORDER BY COUNT(MEMBER_ID) DESC LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT