-- 코드를 입력하세요
SELECT BK.AUTHOR_ID, AUT.AUTHOR_NAME, CATEGORY, SUM(BKS.SALES*BK.PRICE) AS TOTAL_SALES
FROM BOOK BK JOIN BOOK_SALES BKS ON BK.BOOK_ID = BKS.BOOK_ID
             JOIN AUTHOR AUT ON BK.AUTHOR_ID = AUT.AUTHOR_ID
WHERE sales_date <= DATE('2022-01-31')
GROUP BY BK.AUTHOR_ID, CATEGORY
ORDER BY BK.AUTHOR_ID ASC, category DESC