-- 코드를 입력하세요
SELECT PD.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT PD JOIN FOOD_ORDER OD ON PD.PRODUCT_ID =  OD.PRODUCT_ID
WHERE PRODUCE_DATE LIKE '2022-05%'
GROUP BY PD.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PD.PRODUCT_ID ASC