-- 코드를 입력하세요
SELECT APT.APNT_NO, PT.PT_NAME, PT.PT_NO, APT.MCDP_CD, DT.DR_NAME, APT.APNT_YMD
FROM PATIENT PT LEFT JOIN APPOINTMENT APT ON PT.PT_NO = APT.PT_NO
                RIGHT JOIN DOCTOR DT ON DT.DR_ID = APT.MDDR_ID
WHERE APNT_CNCL_YN LIKE 'N' AND APT.MCDP_CD LIKE 'CS'
                            AND APNT_YMD LIKE '2022-04-13%'
ORDER BY APT.APNT_YMD ASC;